#!/usr/bin/env perl -l

use strict;
use warnings;

use File::Basename qw(dirname);
use Cwd qw(abs_path);

use lib dirname(abs_path $0) . '/lib';

use Powr;
use PowrFormatter;

my $powr      = Powr->new;
my $formatter = PowrFormatter->new({powr => $powr});

print $formatter->short;
